persistence true
persistence_location /mosquitto/data/
log_dest stdout
listener 8883
allow_anonymous false
password_file /mosquitto/data/passwordfile
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/data/server.key
tls_version tlsv1.2
