persistence true
persistence_location /mosquitto/data/
log_dest stdout
listener 8883
allow_anonymous false
password_file /mosquitto/data/passwordfile
cafile /mosquitto/config/ca.crt
certfile /mosquitto/config/server.crt
keyfile /mosquitto/config/server.key
tls_version tlsv1.2
