apiVersion: 1

datasources:
  - name: DAQNavi TimescaleDB
    uid: daqnavi-timescale
    type: postgres
    access: proxy
    url: pg:5432
    user: admin
    secureJsonData:
      password: testpass
    jsonData:
      database: daq_navi_dev
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false

  - name: DAQNavi InfluxDB
    uid: daqnavi-influx
    type: influxdb
    access: proxy
    url: http://influx:8086
    secureJsonData:
      token: local-dev-token
    jsonData:
      version: Flux
      organization: mddp
      defaultBucket: daq_telemetry
      tlsSkipVerify: false
    editable: false
